table Fato_Eventos_Westgard

	/// UMA LINHA = UM EVENTO DE VIOLACAO.
	///
	/// Nao confundir com "um resultado marcado". Um 6x N3/R2 e UM evento e
	/// marca SEIS resultados; um painel que soma marcacoes e chama de eventos
	/// infla a contagem sem que ninguem perceba (ADR-045).
	///
	/// GRAO DIFERENTE POR PRODUTO, E ISSO ESTA DECLARADO
	///
	/// A Bioquimica publica o grao de evento: 14 campos, com detector, escopo,
	/// N, R, corrida inicial e evidencia. A Hematologia de producao ainda roda
	/// o RegistrarEventosWestgard legado, que grava (corrida x analito x nivel)
	/// com 8 campos -- e nesse formato R_4s, 2of3_2s, 3_1s e 6x sao
	/// estruturalmente invisiveis, porque exigem visao multi-nivel.
	///
	/// A coluna Grao diz qual e qual. As medidas que dependem de N e R
	/// devolvem BLANK para o grao legado em vez de um numero errado: dado que
	/// nao sustenta a conta nao vira conta.

	column Data
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: Data

	column RUN
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: RUN

	column Analito
		dataType: string
		summarizeBy: none
		sourceColumn: Analito

	column Niveis
		dataType: string
		summarizeBy: none
		sourceColumn: Niveis

	column Regra
		dataType: string
		summarizeBy: none
		sourceColumn: Regra

	column Detector
		dataType: string
		summarizeBy: none
		sourceColumn: Detector

	column Escopo
		dataType: string
		summarizeBy: none
		sourceColumn: Escopo

	column Classe
		dataType: string
		summarizeBy: none
		sourceColumn: Classe

	column N_Niveis
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: N_Niveis

	column R_Corridas
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: R_Corridas

	column RUN_Inicial
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: RUN_Inicial

	column Classificacao
		dataType: string
		summarizeBy: none
		sourceColumn: Classificacao

	column Z_Max
		dataType: double
		summarizeBy: none
		sourceColumn: Z_Max

	column Produto
		dataType: string
		summarizeBy: none
		sourceColumn: Produto

	column Grao
		dataType: string
		summarizeBy: none
		sourceColumn: Grao

	measure N_Eventos_Violacao =
			/// Quantas vezes a REGRA disparou. So conta onde o grao e de evento.
			CALCULATE (
			    COUNTROWS ( Fato_Eventos_Westgard ),
			    Fato_Eventos_Westgard[Grao] = "EVENTO"
			)
		formatString: #,0
		displayFolder: 05 Westgard

	measure N_Resultados_Marcados =
			/// Quantos RESULTADOS ficaram marcados. Um evento N niveis x R
			/// corridas marca N*R resultados -- e por isso que este numero e
			/// maior que o de eventos, e por isso que os dois precisam existir.
			CALCULATE (
			    SUMX (
			        Fato_Eventos_Westgard,
			        COALESCE ( Fato_Eventos_Westgard[N_Niveis], 1 )
			            * COALESCE ( Fato_Eventos_Westgard[R_Corridas], 1 )
			    ),
			    Fato_Eventos_Westgard[Grao] = "EVENTO"
			)
		formatString: #,0
		displayFolder: 05 Westgard

	measure N_Corridas_Com_Violacao =
			/// Corridas distintas com pelo menos um evento. Vale nos dois graos,
			/// porque so depende do RUN.
			DISTINCTCOUNT ( Fato_Eventos_Westgard[RUN] )
		formatString: #,0
		displayFolder: 05 Westgard

	measure Eventos_sem_grao_de_evento =
			/// Quantas linhas vem do registro legado. Diferente de zero, as tres
			/// medidas acima nao cobrem o produto inteiro -- e melhor ver isso
			/// num cartao do que descobrir depois.
			CALCULATE (
			    COUNTROWS ( Fato_Eventos_Westgard ),
			    Fato_Eventos_Westgard[Grao] <> "EVENTO"
			)
		formatString: #,0
		displayFolder: 09 Diagnostico

	partition Fato_Eventos_Westgard = m
		mode: import
		source =
				let
				    // A aba NAO e ListObject: le-se a planilha e promove-se a
				    // linha 3, porque as duas primeiras sao titulo e totalizador.
				    Bruto = (caminho) =>
				        let
				            F = Excel.Workbook(File.Contents(caminho), null, true),
				            Aba = F{[Item="Eventos_Westgard", Kind="Sheet"]}[Data],
				            SemTopo = Table.Skip(Aba, 2),
				            ComCab = Table.PromoteHeaders(SemTopo, [PromoteAllScalars=true])
				        in
				            ComCab,

				    // NORMALIZACAO DOS DOIS GRAOS PARA UM ESQUEMA SO.
				    //
				    // O que o legado nao tem vira null, nao zero: zero afirmaria
				    // que o detector rodou e nao achou nada, e o que aconteceu e
				    // que ele nem existe naquele formato.
				    Padrao = (t, produto, grao) =>
				        let
				            temNiveis = List.Contains(Table.ColumnNames(t), "Níveis"),
				            comNiveis = if temNiveis
				                then Table.RenameColumns(t, {{"Níveis","Niveis"}})
				                else Table.RenameColumns(t, {{"Nível","Niveis"}}),
				            comZ = Table.RenameColumns(comNiveis,
				                {{"Z_Max","Z_Max"}}, MissingField.Ignore),
				            comZ2 = if List.Contains(Table.ColumnNames(comZ), "Z-Score")
                                then Table.RenameColumns(comZ, {{"Z-Score","Z_Max"}})
                                else comZ,
				            comCls = Table.RenameColumns(comZ2,
				                {{"Classificação","Classificacao"}}, MissingField.Ignore),
				            comEv = Table.RenameColumns(comCls,
				                {{"N","N_Niveis"}, {"R","R_Corridas"}}, MissingField.Ignore),
				            faltantes = List.Difference(
				                {"Data","RUN","Analito","Niveis","Regra","Detector",
				                 "Escopo","Classe","N_Niveis","R_Corridas","RUN_Inicial",
				                 "Classificacao","Z_Max"},
				                Table.ColumnNames(comEv)),
				            completo = List.Accumulate(faltantes, comEv,
				                (est, c) => Table.AddColumn(est, c, each null)),
				            comProd = Table.AddColumn(completo, "Produto", each produto, type text),
				            comGrao = Table.AddColumn(comProd, "Grao", each grao, type text),
				            so = Table.SelectColumns(comGrao,
				                {"Data","RUN","Analito","Niveis","Regra","Detector",
				                 "Escopo","Classe","N_Niveis","R_Corridas","RUN_Inicial",
				                 "Classificacao","Z_Max","Produto","Grao"}),
				            semVazias = Table.SelectRows(so, each [RUN] <> null)
				        in
				            semVazias,

				    Bio = Padrao(Bruto(pCaminhoQC), "Bioquimica", "EVENTO"),
				    Hem = Padrao(Bruto(pCaminhoHema), "Hematologia", "LEGADO_1N"),
				    Junto = Table.Combine({Bio, Hem}),
				    Tipado = Table.TransformColumnTypes(Junto, {
				        {"Data", type datetime}, {"RUN", Int64.Type},
				        {"Analito", type text}, {"Niveis", type text},
				        {"Regra", type text}, {"Detector", type text},
				        {"Escopo", type text}, {"Classe", type text},
				        {"N_Niveis", Int64.Type}, {"R_Corridas", Int64.Type},
				        {"RUN_Inicial", Int64.Type}, {"Classificacao", type text},
				        {"Z_Max", type number}, {"Produto", type text},
				        {"Grao", type text}})
				in
				    Tipado

	annotation PBI_ResultType = Table
