table Fato_Eventos_Westgard

	/// UMA LINHA = UM EVENTO DE VIOLACAO.
	///
	/// Nao confundir com "um resultado marcado". Um 6x N3/R2 e UM evento e
	/// marca SEIS resultados; um painel que soma marcacoes e chama de eventos
	/// infla a contagem sem que ninguem perceba (ADR-045).
	///
	/// Os dois produtos publicam o MESMO grao, com as mesmas 14 posicoes. Antes
	/// da migracao do motor, a Bioquimica gravava as regras CONCATENADAS numa
	/// celula ("13s+22s+41s+10x") e a Hematologia gravava
	/// (corrida x analito x nivel) -- formato em que R_4s, 2of3_2s, 3_1s e 6x
	/// sao estruturalmente invisiveis, porque exigem ver os niveis juntos.
	///
	/// NOMES POR POSICAO, NAO POR ROTULO
	///
	/// EV_NCOL = 14 e contrato do motor: as posicoes sao fixas. O rotulo da
	/// linha 3 nao e: ja veio como "NÍveis" e "Evidéncia" com o acento
	/// corrompido, e casar por nome falharia sem dizer por que. Le-se pela
	/// ordem, que e o que o motor garante.

	column Data
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: Data

	column RUN
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: RUN

	column Analito
		dataType: string
		summarizeBy: none
		sourceColumn: Analito

	column Niveis
		dataType: string
		summarizeBy: none
		sourceColumn: Niveis

	column Regra
		dataType: string
		summarizeBy: none
		sourceColumn: Regra

	column Detector
		dataType: string
		summarizeBy: none
		sourceColumn: Detector

	column Escopo
		dataType: string
		summarizeBy: none
		sourceColumn: Escopo

	column Classe
		dataType: string
		summarizeBy: none
		sourceColumn: Classe

	column N_Niveis
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: N_Niveis

	column R_Corridas
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: R_Corridas

	column RUN_Inicial
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: RUN_Inicial

	column Evidencia
		dataType: string
		summarizeBy: none
		sourceColumn: Evidencia

	column Classificacao
		dataType: string
		summarizeBy: none
		sourceColumn: Classificacao

	column Z_Max
		dataType: double
		summarizeBy: none
		sourceColumn: Z_Max

	column Area
		dataType: string
		summarizeBy: none
		sourceColumn: Area

	column RUN_Final
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: RUN_Final

	measure N_Eventos_Violacao =
			/// Quantas vezes a REGRA disparou.
			COUNTROWS ( Fato_Eventos_Westgard )
		formatString: #,0
		displayFolder: 05 Westgard

	measure N_Resultados_Marcados =
			/// Quantos RESULTADOS ficaram marcados. Um evento de N niveis por R
			/// corridas marca N*R resultados -- e por isso que este numero e
			/// maior que o de eventos, e por isso que os dois precisam existir.
			SUMX (
			    Fato_Eventos_Westgard,
			    COALESCE ( Fato_Eventos_Westgard[N_Niveis], 1 )
			        * COALESCE ( Fato_Eventos_Westgard[R_Corridas], 1 )
			)
		formatString: #,0
		displayFolder: 05 Westgard

	measure N_Corridas_Com_Violacao =
			/// Corridas distintas com pelo menos um evento. Nao e a uniao das
			/// JANELAS: um evento 6x N3/R2 envolve seis corridas, e o que se
			/// conta aqui e onde o evento foi registrado.
			DISTINCTCOUNT ( Fato_Eventos_Westgard[RUN] )
		formatString: #,0
		displayFolder: 05 Westgard

	measure N_Eventos_Oficiais =
			/// So os detectores oficiais decidem rejeicao. Os longitudinais
			/// (SAME_LEVEL_R*) sao COMPLEMENTAR: entram no trace para explicar,
			/// e nao na conta, porque soma-los multiplicaria as oportunidades de
			/// rejeicao e subiria a falsa rejeicao sem ninguem decidir (ADR-042).
			CALCULATE (
			    COUNTROWS ( Fato_Eventos_Westgard ),
			    Fato_Eventos_Westgard[Classe] = "OFICIAL"
			)
		formatString: #,0
		displayFolder: 05 Westgard

	partition Fato_Eventos_Westgard = m
		mode: import
		source =
				let
				    // 14 POSICOES FIXAS (EV_NCOL). Le-se por ORDEM, nao por
				    // rotulo: o cabecalho da linha 3 ja veio com acento
				    // corrompido, e casar por nome falharia em silencio.
				    NOMES = {"Data","RUN","Analito","Niveis","Regra","Detector",
				             "Escopo","Classe","N_Niveis","R_Corridas",
				             "RUN_Inicial","Evidencia","Classificacao","Z_Max"},

				    Bruto = (caminho, area) =>
				        let
				            F = Excel.Workbook(File.Contents(caminho), null, true),
				            Aba = F{[Item="Eventos_Westgard", Kind="Sheet"]}[Data],
				            // linhas 1 a 3 sao titulo, totalizador e cabecalho
				            Dados = Table.Skip(Aba, 3),
				            Primeiras = Table.SelectColumns(Dados,
				                List.FirstN(Table.ColumnNames(Dados), 14)),
				            Renomeada = Table.RenameColumns(Primeiras,
				                List.Zip({Table.ColumnNames(Primeiras), NOMES})),
				            ComArea = Table.AddColumn(Renomeada, "Area",
				                each area, type text),
				            // linha sem RUN e sobra de formatacao da aba
				            Limpa = Table.SelectRows(ComArea,
				                each [RUN] <> null and [RUN] <> "")
				        in
				            Limpa,

				    Bio = Bruto(pCaminhoQC, "Bioquimica"),
				    Hem = Bruto(pCaminhoHema, "Hematologia"),
				    Junto = Table.Combine({Bio, Hem}),
				    Tipado = Table.TransformColumnTypes(Junto, {
				        {"Data", type datetime}, {"RUN", Int64.Type},
				        {"Analito", type text}, {"Niveis", type text},
				        {"Regra", type text}, {"Detector", type text},
				        {"Escopo", type text}, {"Classe", type text},
				        {"N_Niveis", Int64.Type}, {"R_Corridas", Int64.Type},
				        {"RUN_Inicial", Int64.Type}, {"Evidencia", type text},
				        {"Classificacao", type text}, {"Z_Max", type number},
				        {"Area", type text}}),
				    // A JANELA DO EVENTO, PARA O USUARIO NAO TER DE CALCULAR.
				    // RUN_Inicial e o comeco; o RUN da linha e o fim.
				    ComFinal = Table.AddColumn(Tipado, "RUN_Final",
				        each [RUN], Int64.Type)
				in
				    ComFinal

	annotation PBI_ResultType = Table
